### ISSUE TITLE
Breaking API change

### ISSUE THREAD

**Issue by paulerickson** [myuw-web-components/myuw-profile#24]
I just tried to upgrade from 1.1.0 to 1.3.1 and my login button disappeared!  It took me a while to troubleshoot the cause, since there was no error reported.  Looking at the diff, it's a totally different API now, so I think a major version increment is needed for consumers to tell whether a new version is safe or will require client changes.

**Comment by davidmsibley** [comment]
Sorry you ran into that. We kind of missed the chance to take advantage of a 0.x.x versioning stage with our current set of myuw-web-components. What resulted was active development and breaking changes happening in the 1.x.x versions.

At the moment, we've solidified that any change to how these components get delivered or loaded will result in a major version change. However, at the moment, the APIs are still considered fluid, mainly because the components are at various states of readiness. I am hoping we can use the upcoming dev sprint to plan and communicate a date after which we consider API changes as breaking, and we fully convert to semver.

**Comment by thevoiceofzeke** [comment]
Thanks for bringing this up Paul. 

To add a little to what Dave said: The kick-off meeting for the UW Design System/Web Components efforts is planned for the first week of December. My hope is that we'll have adopted semantic versioning by that point, and we'll mark the occasion with a version 2.0.0 release of the full suite of components. In the mean time, I'll be more diligent about communicating any major changes to the handful of folks actively using them.

**Comment by paulerickson** [comment]
Cool, thanks for the explanation, guys.
